name: anthonyswebsite
favicon: null
layout_spectrum: 0.4601784339174628
typography_spectrum: 0.8976374445483088
title: DynamicMan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3d0e1'
    - '#7a9ec2'
    - '#fcfef9'
    - '#5273a8'
    - '#1b1c1e'
  brandStrength: 0.4990766542032361
  lightness: 0.7420313903130591
  saturation: 0.06428017560392618
  rhythmicContrast: 0.6129695232957602
purpose: []
